import test from 'node:test';
import assert from 'node:assert/strict';
import {createCity,build,analyze,tick,serialize,deserialize,index,terraform,buildBridge,removeNetwork,launchSatellite,optimizeOperations} from '../dist/engine.mjs';
import {climate} from '../dist/climate.mjs';
function supplied(){const c=createCity(false);for(let x=26;x<32;x++)for(const tool of ['road','wire','pipe'])assert(build(c,index(x,16),tool).ok);assert(build(c,index(27,17),'power').ok);assert(build(c,index(28,17),'pump').ok);return c;}
test('time and season change solar production; darkness shuts solar down',()=>{const c=supplied();assert(build(c,index(26,17),'solar').ok);c.operations.thermal=0;c.environment.season='summer';c.environment.hour=12;analyze(c);const noon=c.metrics.powerCapacity;assert(noon>0);c.environment.hour=8;analyze(c);assert(c.metrics.powerCapacity<noon);const morning=climate(c).sunDirection;c.environment.hour=16;assert.notDeepEqual(climate(c).sunDirection,morning);c.environment.hour=0;analyze(c);assert(climate(c).night);assert.equal(c.metrics.powerCapacity,0);assert.equal(c.metrics.environment.irradiance,0);});
test('terrain edits reject occupied land and preserve state through saves',()=>{const c=createCity(false),id=index(20,20);assert(terraform(c,id,'raise').ok);assert.equal(c.tiles[id].elevation,1);assert(terraform(c,id,'flatten',4).ok);assert.equal(c.tiles[id].elevation,4);assert(build(c,id,'pipe').ok);const cash=c.cash;assert.equal(terraform(c,id,'lower').ok,false);assert.equal(c.cash,cash);assert(removeNetwork(c,id,'pipe').ok);assert(terraform(c,id,'lower').ok);assert.equal(deserialize(serialize(c)).tiles[id].elevation,3);});
test('surface demolition preserves buried networks; targeted removal cuts only chosen utility',()=>{const c=supplied(),id=index(30,16);assert(build(c,id,'bulldoze').ok);assert(c.tiles[id].wire);assert(c.tiles[id].pipe);assert(removeNetwork(c,id,'wire').ok);assert(!c.tiles[id].wire);assert(c.tiles[id].pipe);});
test('custom bridge validates endpoints, spans water, and removes as one structure',()=>{const c=createCity(false);const start=index(1,16),end=index(8,16);assert(buildBridge(c,start,index(9,17)).ok===false);assert(buildBridge(c,start,end,{style:'arch',height:60,width:20}).ok);assert.equal(c.bridges.length,1);const waterId=c.bridges[0].tiles.find(i=>c.tiles[i].terrain==='water');assert(Number.isInteger(waterId));const d=deserialize(serialize(c));assert.equal(d.bridges[0].height,60);assert(build(d,index(5,16),'bulldoze').ok);assert.equal(d.bridges.length,0);assert(d.tiles[waterId].terrain==='water');});
test('launch requires services, funds, and safe weather',()=>{const c=supplied(),id=index(29,17);assert(build(c,id,'spaceport').ok);c.environment.weather='hail';assert.equal(launchSatellite(c,id).ok,false);c.environment.weather='sun';c.environment.wind=20;const cash=c.cash;assert(launchSatellite(c,id).ok);assert.equal(c.satellites,1);assert.equal(c.cash,cash-12000);assert.equal(deserialize(serialize(c)).satellites,1);});
test('environment design reduces heat and vehicles without erasing embodied carbon',()=>{const c=createCity();for(let i=0;i<12;i++)tick(c);c.environment.season='summer';c.environment.hour=12;analyze(c);const before={...c.metrics.environment};const site=c.tiles.find(t=>t.terrain==='land'&&t.type==='empty');build(c,site.id,'commercial');const carbon=c.embodiedCarbon;Object.assign(c.design,{trees:90,greenRoofs:90,coolSurfaces:90,electricMobility:90,lowCarbonMaterials:90});analyze(c);assert(c.metrics.environment.meanSurface<before.meanSurface);assert(c.metrics.environment.cars<before.cars);assert.equal(c.embodiedCarbon,carbon);assert.equal(deserialize(serialize(c)).design.greenRoofs,90);});
test('optimization previews preserve city state and feasible candidates retain coverage',()=>{const c=createCity();const before=serialize(c),r=optimizeOperations(c);assert.equal(serialize(c),before);assert.equal(r.scenarios,12);assert(r.best);assert(r.best.cost<=r.baseline.cost);assert(r.best.power>=99);assert(r.best.water>=99);});
test('dam placement and reservoir capacity remain bounded',()=>{const c=createCity(false);assert.equal(build(c,index(20,20),'dam').ok,false);const water=c.tiles.find(t=>t.terrain==='water'&&t.x>0&&t.x<29&&c.tiles[t.id+1].terrain==='water'&&c.tiles[t.id+2].terrain==='water'&&c.tiles[t.id-1].terrain==='land');assert(water);assert(build(c,water.id,'dam').ok);assert.equal(c.metrics.network.stockCapacity,50000);assert(c.storage<=c.metrics.network.stockCapacity);assert.equal(deserialize(serialize(c)).storage,c.storage);});
