const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../dist'),OUT=path.join(ROOT,'../docs/screenshots'),mode=process.argv[2]||'three';
(async()=>{const b=await chromium.launch({...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--single-process','--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],env:process.env});try{const p=await b.newPage({viewport:{width:1000,height:750}}),errors=[];p.setDefaultTimeout(60000);p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE',e.message)});p.on('console',m=>{if(m.type()==='error'){errors.push(m.text().slice(0,180));console.log(m.text().slice(0,180))}});await p.route('http://city.test/**',r=>{let n=decodeURIComponent(new URL(r.request().url()).pathname);if(n==='/')n='/index.html';const f=path.join(ROOT,n);if(!fs.existsSync(f))return r.fulfill({status:404,body:'Not found'});let body=fs.readFileSync(f);if(n==='/app.mjs')body=body.toString()+`\nwindow.__gameTest={get city(){return city},setView,refresh,setOverlay,view,setTool,tick,position,build,get state(){return store.getState().keplerGl.city.mapState;}};`;return r.fulfill({body,contentType:{'.mjs':'text/javascript','.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json'}[path.extname(f)]||'application/octet-stream'});});
 const {createCity,serialize,analyze,build,index}=await import('file://'+ROOT+'/engine.mjs');const c=createCity(false);c.cash=1e7;c.month=2052;c.progression.phase=10;
 for(let x=12;x<32;x++)for(const tool of ['road','pipe','wire'])build(c,index(x,16),tool);build(c,index(15,15),'power');build(c,index(16,15),'pump');
 for(const [x,y,type,level] of [[16,17,'residential',6],[17,17,'residential',10],[18,17,'fire',5],[19,17,'commercial',4],[20,17,'ferris',5]]){build(c,index(x,y),type);Object.assign(c.tiles[index(x,y)],{level,age:36});}analyze(c);
 await p.addInitScript(({save,mode})=>{localStorage.setItem('sc2020-autosave',save);localStorage.setItem('sc2020-graphics','{"shadows":false}');localStorage.setItem('sc2020-renderer',mode);},{save:serialize(c),mode});await p.goto('http://city.test/');await p.locator('#continue-city').click();await p.waitForFunction(()=>window.__gameTest&&document.getElementById('map-loading').style.display==='none');await p.locator('#pause').click();
 await p.evaluate(()=>{const g=window.__gameTest,[longitude,latitude]=g.position(17.5,17.5,0,g.city);g.setView({longitude,latitude,zoom:17.5,pitch:48,bearing:-30,transitionDuration:0});g.refresh({save:false});});
 await p.screenshot({path:OUT+'/v050-'+mode+'-detail.png'});console.log(mode,'surface rendered');
 // Real UI month stepping drives the production engine, even while paused.
 const before=await p.evaluate(()=>window.__gameTest.city.month);await p.getByRole('button',{name:'+1 month',exact:true}).click();const after=await p.evaluate(()=>window.__gameTest.city.month);if(after!==before+1)throw Error('Month step failed');
 await p.evaluate(()=>{const g=window.__gameTest;g.city.environment.hour=23;g.city.environment.lighting='night';g.refresh({save:false});});await p.screenshot({path:OUT+'/v050-'+mode+'-night.png'});console.log(mode,'night rendered');
 await p.evaluate(()=>{const g=window.__gameTest;g.view.underground=true;g.view.network='all';g.view.cutDepth=45;g.refresh({save:false});});await p.screenshot({path:OUT+'/v050-'+mode+'-underground.png'});console.log(mode,'underground rendered');
 await p.evaluate(()=>{const g=window.__gameTest;g.view.underground=false;g.city.environment.hour=13;g.city.environment.lighting='day';g.setOverlay('surface');g.refresh({save:false});});await p.screenshot({path:OUT+'/v050-'+mode+'-analytics.png'});console.log(mode,'analytics rendered');
 console.log('ERRORS',JSON.stringify(errors));if(errors.length)throw Error('Browser errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
